MyWebCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using BLL;
using Microsoft.AspNetCore.Mvc;
using Model;

namespace MyWebCore
{

    public class HomeController : BaseContoller
    {
        INewsService _newsService;
        IFriendlyLinkService _friendlyLinkService;
        public HomeController(INewsService newsService, IFriendlyLinkService friendlyLinkService)
        {
            _newsService = newsService;
            _friendlyLinkService = friendlyLinkService;
        }
        public IActionResult Index()
        {
            ViewBag.zxzx = _newsService.GetAll().Where(s=>s.Type == "最新资讯").OrderByDescending(s=>s.PublishedTime).Take(10).ToList();
            ViewBag.cgal = _newsService.GetAll().Where(s => s.Type == "成功案例").OrderByDescending(s => s.PublishedTime).Take(10).ToList();
            ViewBag.fwxm = _newsService.GetAll().Where(s => s.Type == "服务项目").OrderByDescending(s => s.PublishedTime).Take(10).ToList();
            ViewBag.fwxm1 = _newsService.GetAll().Where(s => s.Type == "服务项目1").OrderByDescending(s => s.PublishedTime).Take(10).ToList();
            ViewBag.tpcs = _newsService.GetAll().Where(s => s.Type == "投票小常识").OrderByDescending(s => s.PublishedTime).Take(10).ToList();
            ViewBag.cjwt = _newsService.GetAll().Where(s => s.Type == "常见问题").OrderByDescending(s => s.PublishedTime).Take(10).ToList();
            return View();
        }
        public IActionResult GetNewsInfo(int id)
        {
            News news = _newsService.GetById(id);
            return View("NewsInfo",news);
        }
        public string FootView()
        {
            string html = string.Empty;
            List<FriendlyLink> friendlyLinks = _friendlyLinkService.GetAll().OrderByDescending(s => s.PublishDate).Take(20).ToList();
            foreach (FriendlyLink item in friendlyLinks)
            {
                html += string.Format("<a href='{0}' target='_blank'>{1}</a>&nbsp;|&nbsp;", item.LinkUrl,item.Title);
            }
            
            return html;
        }

        public IActionResult SystemManager()
        {
            return View();
        }

        public IActionResult NewsList(string type)
        {
            ViewBag.NewsType = type;
            return View();
        }
        public JsonResult GetNewsList(int page, int limit,string newsType)
        {
            string ab = UnicodeToGB(newsType);
            var newsList = _newsService.GetAll().Where(s=>s.Type == "投票小常识")
                                        .Skip((page-1)*limit)
                                        .Take(limit)
                                        .OrderByDescending(s=>s.PublishedTime)
                                        .Select(a => new {  id=a.Id, title=a.Title, content=a.Content, publishedTime= a.PublishedTime.HasValue?a.PublishedTime.Value.ToShortDateString():"" })
                                        .ToList();

            return Json(new { code = 0, data = newsList, count = _newsService.GetAll().Count() });
        }
        public static string UnicodeToGB(string content)
        {
            Regex objRegex = new Regex("&#x([\\d]{4});", RegexOptions.IgnoreCase);
            Match objMatch = objRegex.Match(content);
            if (objMatch.Success)
            {
                StringBuilder sb = new StringBuilder(content);
                while (objMatch.Success)
                {
                    string code = Convert.ToString(Convert.ToInt32(objMatch.Result("${UnicodeCode}")), 16);
                    byte[] array = new byte[2];
                    array[0] = (byte)Convert.ToInt32(code.Substring(2), 16);
                    array[1] = (byte)Convert.ToInt32(code.Substring(0, 2), 16);

                    sb.Replace(objMatch.Value, Encoding.Unicode.GetString(array));

                    objMatch = objMatch.NextMatch();
                }
                return sb.ToString();
            }
            else
            {
                return content;
            }
        }


        //public IActionResult Contact()
        //{
        //    ViewData["Message"] = "Your contact page.";

        //    return View();
        //}

        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

MyWebCore/Controllers/PublishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL;
using Microsoft.AspNetCore.Mvc;
using Model;

namespace MyWebCore.Controllers
{
    public class PublishController : Controller
    {
        INewsService _newsService;
        IFriendlyLinkService _friendlyLinkService;
        public PublishController(INewsService newsService, IFriendlyLinkService friendlyLinkService)
        {
            _newsService = newsService;
            _friendlyLinkService = friendlyLinkService;
    }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult PublishNews()
        {
            try
            {
                string publishBy = Request.Form["account"];
                if(publishBy != "zhengwei")
                {
                    throw new Exception("发布人有误！");
                }
                string title = Request.Form["title"];
                string content = Request.Form["content"]; 
                    string newstype = Request.Form["newstype"];
                News news = new News();
                news.Title = title;
                news.PublishedBy = publishBy;
                news.PublishedTime = DateTime.Now;
                news.Content = content;
                news.BrowsedTimes = 1000;
                news.Type = newstype;
                _newsService.Add(news);
            }
            catch (Exception ex)
            {

                throw new Exception("发布出错");
            }
            return Content("OK");
        }
        public IActionResult PublishFriendlylink()
        {
            try
            {
                string friendlyUse = Request.Form["friendlyUse"];
                if (friendlyUse != "zhengwei")
                {
                    throw new Exception("发布人有误！");
                }
                string url = Request.Form["friendlylink"];
                string friendlyName = Request.Form["friendlyName"];
                FriendlyLink friendlyLink = new FriendlyLink();
                friendlyLink.LinkUrl = url;
                friendlyLink.Title = friendlyName;
                friendlyLink.PublishDate = DateTime.Now;
                _friendlyLinkService.Add(friendlyLink);
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
            return Content("OK");
        }
    }
}

MyWebCore/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MyWebCore/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyWebCore/Views/Home/NewsInfo.cshtml
@model Model.News
@{
    ViewData["Title"] = "NewsInfo";
}
<table width="100%" border="0" cellspacing="0" cellpadding="0">

    <tr>
        <td></td>
    </tr>

    <tr>
        <td align="center">
            <table width="1001" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff">
                <tr>
                    <td></td>
                    <td height="210" colspan="3" valign="top"><img src="../../images/hd.jpg" width="982" height="210"></td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td height="10" colspan="3" valign="top"></td>
                    <td></td>
                </tr>
                <tr>
                    <td width="9"></td>
                    <td width="744" valign="top" style="background-image:url(../../image/rbg.jpg); background-position:bottom; background-repeat:no-repeat;">
                        <table width="745" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td height="36" background="../../images/ar.jpg">
                                    <table width="745" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td height="3" colspan="4"></td>
                                        </tr>
                                        <tr>
                                            <td width="25">&nbsp;</td>
                                            <td width="227" align="left" style="font-size:14px; font-weight:bold;">最新资讯</td>
                                            <td width="485" align="right">你现在的位置：<a href="/">首页</a>&nbsp;>&nbsp;<a href="#">@Model.Type</a></td>
                                            <td width="8">&nbsp;</td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td height="15"></td>
                            </tr>
                            <tr>
                                <td align="center">
                                    <table width="710" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td>

                                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                    <tr>
                                                        <td align="center">

                                                            <div align="center" style="padding-top:10px; font-size:16px; color:#000000; line-height:150%;">
                                                                <font color="#000000"><strong>@Model.Title</strong></font>
                                                            </div>
                                                            <div align="center" class="STYLE1111">
                                                                发布人：@Model.PublishedBy&nbsp;&nbsp;
                                                                时间：@Model.PublishedTime&nbsp;&nbsp;&nbsp;
                                                                浏览：<font color="red">
                                                                    <script src="static/js/5_145_1.js"></script>
                                                                </font>
                                                            </div>
                                                            <div align="center"><span class="STYLE1111">-----------------------------------------------------------------------------------------------------</span></div>

                                                            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                                <tr>
                                                                    <td>
                                                                        <div style="width:100%;text-align:left; padding:0px;overflow-x:hidden; color:#000000">
                                                                              @Html.Raw(System.Net.WebUtility.UrlDecode(@Model.Content))
                                                                            <p style="text-align: center;"><img alt="刷票公司" src="../../images/dbc025ff78893294cb545109590482bc.jpg" style="width: 450px; height: 418px;"></p>
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                            <br>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td height="10"></td>
                                        </tr>

                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td height="15"></td>
                            </tr>
                        </table>
                    </td>

                    <td width="9"></td>
                    <td width="228" height="200" valign="top" style="background-image:url(../../image/lbg.jpg); background-position:bottom; background-repeat:no-repeat;">
                        <table width="228" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td height="63" background="../../images/la.jpg">&nbsp;</td>
                            </tr>


                           

                            <tr>
                                <td height="10"></td>
                            </tr>

                            <tr>
                                <td height="10"></td>
                            </tr>

                            <tr>
                                <td height="33" background="../../images/al.jpg">
                                    <table width="228" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td height="3" colspan="2"></td>
                                        </tr>
                                        <tr>
                                            <td width="27">&nbsp;</td>
                                            <td width="201" align="left" style="font-size:14px; font-weight:bold;">联系我们</td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td height="10"></td>
                            </tr>
                            <tr>
                                <td height="200" align="center" valign="top">
                                    <table width="208" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td align="left">
                                                <p>
                                                    <span>
                                                        <span style="line-height:2.5;font-size:12px;">网络投票公司</span><br>
                                                        <span style="line-height:2.5;font-size:12px;">Q&nbsp; Q：3282079595</span>
                                                    </span>
                                                </p>
                                                <p>
                                                    <span>
                                                        <span style="line-height:2.5;font-size:12px;"></span>
                                                        <span style="line-height:2.5;font-size:12px;">电话：18963948278&nbsp; </span><br>
                                                        <span style="line-height:2;font-size:12px;">
                                                            <span style="line-height:2.5;">微信：18963948278</span><br>
                                                            <span style="line-height:2.5;">网络投票公司是一家多元化发展的互联网公司，会员遍布全国，专业从事互联网络投票,代理投票,微信投票,专业投票公司,微信人工投票以及快速提升各大中小活动排名服务。</span>
                                                        </span>
                                                    </span>
                                                </p>

                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>

                            <tr>
                                <td height="15"></td>
                            </tr>
                        </table>
                    </td>

                    <td width="10"></td>
                </tr>
            </table>
        </td>
    </tr>



</table>

MyWebCore/Views/Home/NewsList.cshtml
@{
    ViewData["Title"] = "投票小常识";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/layui/css/layui.css" rel="stylesheet" />
<script src="~/layui/layui.js"></script>

<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td align="center">
            <table width="1001" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td align="center">

                        <table class="layui-hide" id="demo" lay-filter="demo"></table>

                    </td>
                </tr>
            </table>
        </td>
    </tr>
    </table>
    


    <!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->

    <script>
        var newsType ="@ViewBag.NewsType";
        var regex_num_set = /&#(\d+);/g;
        var newsType1 = newsType.replace(regex_num_set, function (_, $1) {
            return String.fromCharCode($1);
        });
        layui.use('table', function () {
            var table = layui.table;

            //第一个实例
            table.render({
                elem: '#demo'
                , height: 760
                , url: '/home/GetNewsList' //数据接口
                , where: { newsType: newsType}
                , page: true //开启分页
                , limit: 30
                , cols: [[ //表头
                    { field: 'id', title: '序号', width: 80, sort: true, fixed: 'left' }
                    , { field: 'title', title: '标题', width: 280 }
                    , { field: 'content', title: '内容', width: 500 }
                    , { field: 'publishedTime', title: '发布时间', widt: 80 }
                ]]
            });
            //监听行单击事件（双击事件为：rowDouble）
            table.on('row(demo)', function (obj) {
                var data = obj.data;

                layer.alert(JSON.stringify(data), {
                    title: '当前行数据：'
                });

                //标注选中样式
                obj.tr.addClass('layui-table-click').siblings().removeClass('layui-table-click');
            });

        });

    </script>

MyWebCore/Views/Home/SystemManager.cshtml
@{
    ViewData["Title"] = "系统管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/js/dist/bootstrap-3.3.7/css/bootstrap.css" rel="stylesheet" />
<script src="~/js/simditor/js/jquery-2.1.4.min.js"></script>
<link href="~/js/simditor/css/simditor.css" rel="stylesheet" />
<script src="~/js/simditor/js/module.min.js"></script>
<script src="~/js/simditor/js/hotkeys.min.js"></script>
<script src="~/js/simditor/js/simditor.min.js"></script>
<script src="~/assets/js/jquery.min.js"></script>
<style>
    .mail-header {
        background-color: #fff;
        border-bottom: 1px solid #ddd;
        font-size: 20px;
        height: 60px;
        line-height: 60px;
        padding-left: 30px;
        padding-right: 30px;
    }

    .mail-body {
        padding: 20px;
    }

    .mail-box {
        border: 1px solid #ddd;
    }

    .form {
        width: 50%;
        margin: 0px;
        padding: 0px;
        border-collapse: collapse;
        border-width: 3px 1px 1px;
        table-layout: fixed;
    }

        .form .formTitle {
            position: relative;
            left: 0px;
            text-align: right;
            white-space: nowrap;
            font-weight: normal;
            width: 90px;
            padding-right: 15px;
        }

        .form .formValue {
            position: relative;
            padding: 5px;
            width: auto;
        }

    .simditor {
        border-left: none;
        border-right: none;
        border-top: none;
    }

    .has-error .form-control {
        border: 1px solid #a4cbff;
    }
</style>
<script>
    var editor;
    $(function () {
        editor = new Simditor({
            textarea: $('#content'),
            toolbar: ['title', 'bold', 'italic', 'underline', 'strikethrough', 'color', '|', 'ol', 'ul', 'blockquote', 'code', 'table', '|', 'link', 'image', 'hr', '|', 'indent', 'outdent']
        });
    });
 function submitForm()
    {
        var content = $("#content").val();
        var account = $("#account").val();
        var title = $("#title").val();
     var newstype = $("#newType").val();
     if (content == "" || content == null) {
         alert("内容必填！");
     }
     if (account == "" || account == null) {
         alert("发布人必填！");
     }
     if (title == "" || title == null) {
         alert("主题必填！");
     }
     if (newstype == "" || newstype == null) {
         alert("类型必填！");
     }
        $.ajax({
            type: "POST",
            url: '@Url.Action("PublishNews", "Publish")',
            data: { account: account, title: title, content: content, newstype: newstype},
            success: function (data) {
                alert("发布成功！");
            }, error: function (req, status, error) {
                alert("发布失败！");
            }
        });


    }
    function AddFriendlink()
    {
        var friendlylink = $("#friendlylink").val();
        var friendlyName = $("#friendlyName").val();
        var friendlyUse = $("#friendlyUse").val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("PublishFriendlylink", "Publish")',
            data: { friendlylink: friendlylink, friendlyName: friendlyName, friendlyUse: friendlyUse},
            success: function (data) {
                alert("发布成功！");
            }, error: function (req, status, error) {
                alert("发布失败！");
            }
        });
    }
</script>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td align="center">
            <table width="1001" border="0" cellspacing="0" cellpadding="0" style="margin-top:200px">
                <tr>
                    <td align="center">
                        <form id="form1">
                            <div class="mail-box">
                                <div class="mail-header">新闻发布</div>
                                <div class="mail-body">
                                    <table class="form">
                                        <tr>
                                            <th class="formTitle">发布人</th>
                                            <td class="formValue">
                                                <input id="account" name="account" type="text" class="form-control required" placeholder="输入多个邮件地址请用英文符号;隔开" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <th class="formTitle">主题</th>
                                            <td class="formValue">
                                                <input id="title" name="title" type="text" class="form-control required" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <th class="formTitle">类型</th>
                                            <td class="formValue">
                                                <select id="newType">

                                                    <option value="最新资讯">最新资讯</option>
                                                    <option value="成功案例">成功案例</option>
                                                    <option value="投票小常识">投票小常识</option>
                                                    <option value="常见问题">常见问题</option>
                                                </select>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="mail-body" style="padding: 0px;">
                                    <textarea id="content" name="content" class="form-control" rows="5"></textarea>
                                </div>
                                <div class="mail-body" style="text-align:center;">
                                    <a href="javascript:void()" onclick="submitForm()" class="btn btn-primary" style="margin-right: 5px;"><i class="fa fa-reply"></i>发布</a>
                                    @*<a href="javascript:void()" class="btn btn-warning"><i class="fa fa-pencil"></i>存为草稿</a>*@
                                </div>
                            </div>
                        </form>
                        <fieldset style="width:auto;line-height:15px;height:70px;overflow:auto;padding:20px" id="dvTableContainer">

                            <table>
                                <tr>
                                    <td class="formValue" colspan="3">
                                        地址：<input id="friendlylink" type="text" /> 名称：<input id="friendlyName" type="text" /> 用户名 <input id="friendlyUse" type="text" />
                                        <input type="button" onclick="AddFriendlink()" value="新增友连接" />
                                    </td>
                                </tr>
                            </table>
                        </fieldset>
                    </td>
                </tr>
            </table>

          
        </td>
    </tr>
</table>